import { MemberType } from '../_types/member-type';

export const members = [
	{
		id: 1,
		columnId: '4',
		fullName: 'Andrzej Nowicki',
		email: 'andrzej.nowicki@example.com',
		phoneNumber: '123-456-789',
		dateOfBirth: '1990-05-15',
		specialization: {
			domain: 'Frontend',
			role: 'React/Next.js',
		},
		nameOfUniversityOrOccupation: 'Uniwersytet Informatyczny',
		githubAccount: 'andrzejonowicki',
		programingLanguages: 'JavaScript, HTML, CSS',
		graphicInspiration: 'Sztuka cyfrowa, projektowanie UI/UX',
		proficientGraphicTools: 'Adobe Photoshop, Sketch',
		experience: '5 lat doświadczenia w programowaniu frontend',
		finishedProject: 'Strona internetowa e-commerce dla firmy XYZ',
		english_Level: 'b2',
		learningGoals: 'Badanie machine learning w web development',
		goalOfAcademyParticipation: 'Praktyki zawodowe',
		practicesStart: '2023-02-01',
		practicesEnd: '2023-05-01',
		additionalInformation:
			'Pasjonat projektów open source i aktywny uczestnik społeczności programistycznej.',
		assignedToProjectId: '',
		range: 3,
		note: 'Tekst notatki',
	},
	{
		id: 2,
		columnId: '3',
		fullName: 'Anna Kowalska',
		email: 'anna.kowalska@example.com',
		phoneNumber: '987-654-321',
		dateOfBirth: '1995-08-23',
		specialization: {
			domain: 'Backend',
			role: 'Node.js/Express',
		},
		nameOfUniversityOrOccupation: 'Politechnika Warszawska',
		githubAccount: 'annakowalska_dev',
		programingLanguages: 'JavaScript, Python',
		graphicInspiration: 'Wizualizacja danych, minimalistyczny design',
		proficientGraphicTools: 'Matplotlib, Tableau',
		experience: '3 lata doświadczenia w programowaniu backend',
		finishedProject: 'API do aplikacji do czasu rzeczywistego',
		english_Level: 'b2',
		learningGoals: 'Badanie architektury mikrousług',
		goalOfAcademyParticipation: 'Praktyki zawodowe',
		practicesStart: '2023-03-15',
		practicesEnd: '2023-06-15',
		additionalInformation:
			'Z entuzjazmem podchodzę do udziału w projektach open source i tworzenia skalowalnych systemów.',
		assignedToProjectId: '',
		range: 2,
		note: 'Dodatkowy tekst notatki',
	},
	{
		id: 3,
		columnId: '2',
		fullName: 'Piotr Nowak',
		email: 'piotr.nowak@example.com',
		phoneNumber: '555-123-456',
		dateOfBirth: '1988-12-10',
		specialization: {
			domain: 'Frontend',
			role: 'React/Next.js',
		},
		nameOfUniversityOrOccupation: 'Uniwersytet Śląski',
		githubAccount: 'piotrnowak_dev',
		programingLanguages: 'JavaScript, Next.js',
		graphicInspiration:
			'Nowoczesny design interfejsu, interaktywne aplikacje internetowe',
		proficientGraphicTools: 'Figma, Adobe XD',
		experience: '7 lat doświadczenia w programowaniu fullstack',
		finishedProject: 'System rezerwacji online dla biura podróży',
		english_Level: 'b2',
		learningGoals: 'Opanowanie GraphQL i architektury serverless',
		goalOfAcademyParticipation: 'Praktyki zawodowe',
		practicesStart: '2023-04-01',
		practicesEnd: '2023-07-01',
		additionalInformation:
			'Aktywny uczestnik projektów open source i orędownik praktyk czystego kodu.',
		assignedToProjectId: '',
		range: 3,
		note: 'Dodatkowe uwagi na temat projektu',
	},
	{
		id: 4,
		columnId: '5',
		fullName: 'Anna Kowalska',
		email: 'anna.kowalska@example.com',
		phoneNumber: '987-654-321',
		dateOfBirth: '1995-08-22',
		specialization: {
			domain: 'Backend',
			role: 'Node.js/Express',
		},
		nameOfUniversityOrOccupation: 'Instytut Technologiczny',
		githubAccount: 'annakowalska-dev',
		programingLanguages: 'JavaScript, Python, SQL',
		graphicInspiration: 'Sztuka cyfrowa, Projektowanie UX',
		proficientGraphicTools: 'Adobe Illustrator, Figma',
		experience: '4 lata doświadczenia w programowaniu backend',
		finishedProject: 'API na poziomie przedsiębiorstwa dla XYZ Corporation',
		english_Level: 'c1',
		learningGoals: 'Badanie technologii blockchain w programowaniu',
		goalOfAcademyParticipation: 'Praktyki zawodowe',
		practicesStart: '2023-03-15',
		practicesEnd: '2023-06-15',
		additionalInformation:
			'Aktywny współpracownik w projektach open source i zapalony uczeń w społeczności technicznej.',
		assignedToProjectId: '',
		range: 3,
		note: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
	},
	{
		id: 5,
		columnId: '1',
		fullName: 'Jan Wiśniewski',
		email: 'jan.wisniewski@example.com',
		phoneNumber: '555-123-789',
		dateOfBirth: '1988-11-10',
		specialization: {
			domain: 'Backend',
			role: '.Net',
		},
		nameOfUniversityOrOccupation: 'Akademia Programistyczna',
		githubAccount: 'janwisniewski-dev',
		programingLanguages: 'JavaScript, Java, HTML, CSS',
		graphicInspiration: 'Grafika komputerowa, Projektowanie interfejsów',
		proficientGraphicTools: 'Adobe XD, Canva',
		experience: '6 lat doświadczenia w programowaniu fullstack',
		finishedProject:
			'Aplikacja e-commerce zintegrowana z płatnościami online',
		english_Level: 'b1',
		learningGoals:
			'Pogłębianie wiedzy z zakresu sztucznej inteligencji w aplikacjach webowych',
		goalOfAcademyParticipation: 'Praktyki zawodowe',
		practicesStart: '2023-04-01',
		practicesEnd: '2023-07-01',
		additionalInformation:
			'Entuzjasta otwartego oprogramowania i aktywny uczestnik lokalnych meet-upów programistycznych.',
		assignedToProjectId: '',
		range: 2,
		note: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, turpis vel ultricies feugiat, nibh elit dignissim quam, ac lacinia tellus nulla sit amet arcu.',
	},
	{
		id: 6,
		columnId: '3',
		fullName: 'Karolina Majewska',
		email: 'karolina.majewska@example.com',
		phoneNumber: '111-222-333',
		dateOfBirth: '1993-06-25',
		specialization: {
			domain: 'Frontend',
			role: 'React Native',
		},
		nameOfUniversityOrOccupation: 'Politechnika Programistyczna',
		githubAccount: 'karolinam-dev',
		programingLanguages: 'Dart, Java, Kotlin',
		graphicInspiration: 'Ilustracje cyfrowe, Design interfejsów mobilnych',
		proficientGraphicTools: 'Figma, Adobe Illustrator',
		experience: '3 lata doświadczenia w programowaniu mobilnym',
		finishedProject: 'Aplikacja mobilna dla sektora edukacyjnego',
		english_Level: 'b2',
		learningGoals:
			'Eksploracja rozwiązań związanych z sztuczną inteligencją w aplikacjach mobilnych',
		goalOfAcademyParticipation: 'Praktyki zawodowe',
		practicesStart: '2023-05-01',
		practicesEnd: '2023-08-01',
		additionalInformation:
			'Aktywna uczestniczka hackathonów i pasjonatka tworzenia innowacyjnych rozwiązań mobilnych.',
		assignedToProjectId: '',
		range: 3,
		note: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin aliquam, quam vel lacinia scelerisque, justo turpis bibendum arcu, non tempus dolor urna vel lectus.',
	},
	{
		id: 7,
		columnId: '4',
		fullName: 'Michał Nowak',
		email: 'michal.nowak@example.com',
		phoneNumber: '555-111-222',
		dateOfBirth: '1991-09-18',
		specialization: {
			domain: 'Backend',
			role: 'Node.js/Express',
		},
		nameOfUniversityOrOccupation: 'Akademia Informatyczna',
		githubAccount: 'michalnowak-dev',
		programingLanguages: 'JavaScript, Python, SQL',
		graphicInspiration: 'Grafika komputerowa, Projektowanie interfejsów',
		proficientGraphicTools: 'Adobe XD, Sketch',
		experience: '5 lat doświadczenia w programowaniu backend',
		finishedProject: 'System zarządzania zamówieniami dla firmy XYZ',
		english_Level: 'c1',
		learningGoals:
			'Pogłębianie wiedzy z zakresu mikroserwisów i architektury systemów',
		goalOfAcademyParticipation: 'Praktyki zawodowe',
		practicesStart: '2023-06-01',
		practicesEnd: '2023-09-01',
		additionalInformation:
			'Aktywny członek społeczności programistycznej i entuzjasta otwartego oprogramowania.',
		assignedToProjectId: '',
		range: 3,
		note: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, turpis vel ultricies feugiat, nibh elit dignissim quam, ac lacinia tellus nulla sit amet arcu.',
	},
	{
		id: 8,
		columnId: '3',
		fullName: 'Katarzyna Kowalczyk',
		email: 'katarzyna.kowalczyk@example.com',
		phoneNumber: '777-333-111',
		dateOfBirth: '1985-03-10',
		specialization: {
			domain: 'Others',
			role: 'Grafika',
		},
		nameOfUniversityOrOccupation: 'Akademia Sztuk Pięknych',
		githubAccount: 'kasiakowalczyk-design',
		programingLanguages: 'Brak',
		graphicInspiration: 'Sztuka współczesna, Design graficzny',
		proficientGraphicTools: 'Adobe Illustrator, Photoshop',
		experience: '8 lat doświadczenia w projektowaniu graficznym',
		finishedProject: 'Identyczność wizualna dla firmy ABC',
		english_Level: 'b1',
		learningGoals:
			'Rozwinięcie umiejętności w projektowaniu interaktywnych mediów',
		goalOfAcademyParticipation: 'Praktyki zawodowe',
		practicesStart: '2023-07-01',
		practicesEnd: '2023-10-01',
		additionalInformation:
			'Uczestniczka wielu wystaw sztuki i zdobywczyni nagrody w konkursie projektowania graficznego.',
		assignedToProjectId: '',
		range: 1,
		note: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus fermentum elit quis justo semper, nec mattis lectus fermentum.',
	},
	{
		id: 9,
		columnId: '3',
		fullName: 'Michał Lewandowski',
		email: 'michal.lewandowski@example.com',
		phoneNumber: '555-444-333',
		dateOfBirth: '1987-09-05',
		specialization: {
			domain: 'Others',
			role: 'Grafika',
		},
		nameOfUniversityOrOccupation: 'Akademia Sztuk Pięknych',
		githubAccount: 'michallewandowski-art',
		programingLanguages: '',
		graphicInspiration: 'Sztuka współczesna, Design graficzny',
		proficientGraphicTools: 'Adobe Illustrator, InDesign',
		experience: '6 lat doświadczenia w projektowaniu graficznym',
		finishedProject: 'Projekt katalogu artystycznego dla galerii sztuki',
		english_Level: 'a2',
		learningGoals:
			'Doskonalenie umiejętności w projektowaniu multimedialnych treści artystycznych',
		goalOfAcademyParticipation: 'Praktyki zawodowe',
		practicesStart: '2023-08-01',
		practicesEnd: '2023-11-01',
		additionalInformation:
			'Uczestnik licznych wystaw sztuki oraz współtwórca artystycznych projektów społecznościowych.',
		assignedToProjectId: '',
		range: 2,
		note: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur vehicula, augue in fermentum cursus, felis est euismod metus, at convallis sapien velit quis ante.',
	},
	{
		id: 20,
		columnId: '4',
		fullName: 'Magdalena Nowakowska',
		email: 'magdalena.nowakowska@example.com',
		phoneNumber: '555-888-444',
		dateOfBirth: '1986-07-20',
		specialization: {
			domain: 'Backend',
			role: '.Net',
		},
		nameOfUniversityOrOccupation: 'Politechnika Informatyczna',
		githubAccount: 'magdalenanowakowska-dev',
		programingLanguages: '.Net, C#, SQL',
		graphicInspiration: 'Brak',
		proficientGraphicTools: 'Brak',
		experience: '9 lat doświadczenia w programowaniu backend',
		finishedProject: 'System zarządzania zamówieniami dla firmy ABC',
		english_Level: 'b2',
		learningGoals:
			'Eksploracja nowoczesnych rozwiązań w programowaniu .Net',
		goalOfAcademyParticipation: 'Praktyki zawodowe',
		practicesStart: '2023-10-01',
		practicesEnd: '2024-01-01',
		additionalInformation:
			'Członek grupy użytkowników .Net oraz prelegent na konferencjach programistycznych.',
		assignedToProjectId: '1',
		range: 3,
		note: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus eu magna ut nulla commodo laoreet eget nec metus.',
	},
];
