import type { Metadata } from "next"
import "@mantine/core/styles.css"
import "@mantine/dates/styles.css"
import "@mantine/dropzone/styles.css"
import { MantineProvider, ColorSchemeScript } from "@mantine/core"
import { ModalsProvider } from "@mantine/modals"

import TanStackProvider from "@/components/providers/tanstack-provider"

export const metadata: Metadata = {
  title: "Ca-tool",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript defaultColorScheme="light" />
      </head>
      <body>
        <TanStackProvider>
          <MantineProvider defaultColorScheme="light">
            <ModalsProvider>{children}</ModalsProvider>
          </MantineProvider>
        </TanStackProvider>
      </body>
    </html>
  )
}
